#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on using ifconfig

ifconfig | grep -oE 'inet (addr:)?([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v '127.0.0.1' | awk '{print $2}' | sed 's/addr://'
